image:
  repository: nvcr.io/nim/meta/llama-3.1-8b-instruct
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nvcr-secret
resources:
  limits:
    nvidia_gpu: 1
    cpu: "8"
    memory: 32Gi
  requests:
    cpu: "4"
    memory: 16Gi

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: istio
  host: nim-llama.kubernetes.coe.local

env:
  NGC_API_KEY: "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"
  
nodeSelector:
  kubernetes.io/hostname: worker3
  
nimCache:
  hostPath: /mnt/shared_models/nim
