apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-llm
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nim-llm
  template:
    metadata:
      labels:
        app: nim-llm
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      nodeSelector:
        kubernetes.io/hostname: worker3
      containers:
        - name: nim-llm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.resources.limits.nvidia_gpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: NGC_API_KEY
              value: {{ .Values.env.NGC_API_KEY | quote }}

