apiVersion: v1
kind: Service
metadata:
  name: nim-llm
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nim-llm
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000

